### ISSUE TITLE
BSCL EXPORT lädt nicht 

### ISSUE THREAD

**Issue by SonjaKaufmann** [Optinomic/apps#165]
Allerdings dreht der BSCL-Export derzeit im Leeren. Da scheint irgendetwas zu hängen.

**Comment by ottigerb** [comment]
Ich habe die Calculation in die V2 Export-Toolbox verschoben (https://github.com/Optinomic/apps/commit/dd13ccff4aec5bb390b2955adda2cacb48c85de4. ) und nochmals ein `/recompute` angestossen.  

http://optinomic.cust.local/client.new/#/user/app/org.optinomic.export.toolbox.v2.suedhang/template/export zeigt aktuell beim BSCL ein 404-Fehler (not found) an. => Ich denke jetzt ist einfach Geduld gefragt oder Tom muss was richten (vgl. https://github.com/ottigerb/therapy-server/issues/492) -> Bin dran.  

Immerhin hat diese App die neuen Filtertypen bereits erhalten!  :-)

**Comment by ottigerb** [comment]
http://optinomic.cust.local/client.new/#/user/app/org.optinomic.export.toolbox.v2.suedhang/template/export

![bildschirmfoto 2018-01-31 um 18 31 12](https://user-images.githubusercontent.com/2470873/35639260-f30cb88e-06b9-11e8-93c8-f2ac05f0b29b.png)


### Fixed by https://github.com/ottigerb/therapy-server/issues/492
